name: EconomyLand
version: "${pom.version}"
api: [1.0.0]
main: me.onebone.economyland.EconomyLand
author: onebone
depend: [EconomyAPI]

commands:
  land:
    description: "Management command of land"
    usage: "/land <pos1|pos2|buy|sell|give|here|whose|list|invite|kick|invitee|option|options>"
    permission: economyland.command.land;economyland.command.land.pos1;economyland.command.land.pos2;economyland.command.land.buy;economyland.command.land.sell;economyland.command.land.here;economyland.command.land.whose;economyland.command.land.list;economyland.command.land.move;economyland.command.land.invite;economyland.command.land.kick;economyland.command.land.invitee;economyland.command.land.option;economyland.command.land.options;
permissions:
  economyland:
    description: "Includes all permissions for EconomyLand"
    children:
      economyland.command:
        description: "Allows player to use all commands"
        children:
          economyland.command.land:
            description: "Allows player to use /land"
            default: true
            children:
              economyland.command.land.pos1:
                description: "Allows player to use /land pos1"
              economyland.command.land.pos2:
                description: "Allows player to use /land pos2"
              economyland.command.land.buy:
                description: "Allows player to use /land buy"
              economyland.command.land.sell:
                description: "Allows player to use /land sell"
              economyland.command.land.here:
                description: "Allows player to use /land here"
              economyland.command.land.give:
                description: "Allows player to use /land give"
              economyland.command.land.whose:
                description: "Allows player to use /land whose"
              economyland.command.land.list:
                description: "Allows player to use /land list"
              economyland.command.land.move:
                description: "Allows player to use /land move"
              economyland.command.land.kick:
                description: "Allows player to use /land kick"
              economyland.command.land.invite:
                description: "Allows player to use /land invite"
              economyland.command.land.invitee:
                description: "Allows player to use /land invitee"
              economyland.command.land.option:
                description: "Allows player to use /land option"
              economyland.command.land.options:
                description: "Allows player to use /land options"
      economyland.buy:
        description: "Allows player to buy land"
        default: true
      economyland.sell:        
        description: "Allows player to sell land"
        default: true
      economyland.admin:
        description: "EconomyLand admin permission"
        children:
          economyland.admin.sell:
            description: "Allows player to sell others' land"
          economyland.admin.modify:
            description: "Allows player to modify others' land"
          economyland.admin.access:
            description: "Allows player to access others' land"
          economyland.admin.pickup:
            description: "Allows player to pick up items in others' land"
          economyland.admin.invite:
            description: "Allows player to invite player to others' land"
          economyland.admin.kick:
            description: "Allows player to kick player from others' land"
          economyland.admin.give:
            description: "Allows player to change owner of others' land"
          economyland.admin.option:
            description: "Allows player to change option of others' land"
 
